### ISSUE TITLE
Failed to find Electron v7.0.0 for linux-armv7l

### ISSUE THREAD

**Issue by Greenfoot5** [electron/mksnapshot#23]
When running `npm install --save-dev electron-mksnapshot` on my raspbery pi 4, I get this result:
```
> electron-mksnapshot@7.0.0 install /home/pi/Developer/atom/node_modules/electron-mksnapshot
> node ./download-mksnapshot.js

/home/pi/Developer/atom/node_modules/electron-mksnapshot/download-mksnapshot.js:19
  if (err != null) throw err
                   ^

Error: Failed to find Electron v7.0.0 for linux-armv7l at https://github.com/electron/electron/releases/download/v7.0.0/mksnapshot-v7.0.0-linux-armv7l.zip
    at Request.<anonymous> (/home/pi/Developer/atom/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (/home/pi/Developer/atom/node_modules/request/request.js:1066:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:552:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:116:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-mksnapshot@7.0.0 install: `node ./download-mksnapshot.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-mksnapshot@7.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-10-29T19_35_39_121Z-debug.log
```

The log can be found here: https://hastebin.com/igonihavoh.log

I have run `npm install electron --save-dev` which told me it had installed electron.

**Comment by jkleinsc** [comment]
Unfortunately as of Electron 6-0-x we removed native arm/arm64 mksnapshot binaries due to chromium incompatibilities (see  https://github.com/electron/electron/pull/17561 for more details).  If you need to generate snapshots for arm or arm64 you need to manually download the proper mksnapshot binary onto an x64 system and generate the binary there.

For example in order to generate an armv7l snapshot for Electron 7.2.3, you would need to download [mksnapshot-v7.2.3-linux-armv7l-x64.zip](https://github.com/electron/electron/releases/download/v7.2.3/mksnapshot-v7.2.3-linux-armv7l-x64.zip) from https://github.com/electron/electron/releases/tag/v7.2.3
