### ISSUE TITLE
Compiled binaries downloaded by mksnapshot broken?

### ISSUE THREAD

**Issue by ghost** [electron/mksnapshot#3]
Looks like mksnapshot compiled binaries downloaded by electron-mksnapshot wrong compiled. When I downloading prebuilt binaries for arm/armv7l I got Intel 80836 binaries.
`file mksnapshot` output:
`mksnapshot: ELF 32-bit LSB  shared object, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.26, BuildID[sha1]=8b1a63cf158c934666279b6539cfa945502264c5, not stripped`

So, I'd like to compile mksnapshot separately from Electron on my machine, where i can found sources for it?

**Comment by hypersad** [comment]
Any news? :(

**Comment by kevinsawicki** [comment]
@hypersad which version of `mksnapshot` and `electron` are you using?

**Comment by hypersad** [comment]
@kewinsawicki I need mksnapshot for building Atom. Defined electronVersion to 1.6.0 and mksnapshot to ~1.6 in config.

**Comment by kevinsawicki** [comment]
@hypersad can you try setting running:

```bash
npm --arch=armv7l --platform=linux install electron-mksnapshot@1.6.0
```

and see if that downloads the right version?

**Comment by hypersad** [comment]
I'll try it when i come home, but didn't think that it help me, because I tried some versions from china mirror and they returns Intel 80836

**Comment by hypersad** [comment]
Still getting Intel 80836 binaries...
Install log can be found [here](https://pastebin.com/VY4iDSrp)

**Comment by kevinsawicki** [comment]
@hypersad can you download https://github.com/electron/electron/releases/download/v1.6.0/mksnapshot-v1.6.0-linux-armv7l.zip directly and confirm it works as expected?

**Comment by hypersad** [comment]
Again Intel 80836, again 'Exec format error'...

**Comment by nonnymoose** [comment]
@hypersad  @kevinsawicki Is [this](https://github.com/electron-archive/node-mksnapshot) the source?

**Comment by hypersad** [comment]
Any news? We need mksnapshot for trying to build Atom on armv7l :(

**Comment by hypersad** [comment]
Maybe I should create an issue in electron?

**Comment by mathuin** [comment]
@hypersad I made an issue https://github.com/electron/electron/issues/11413 because I didn't know mksnapshot had its own repository.  This problem has not yet been fixed, and now your unmaintained repository no longer builds -- not your fault, that's what unmaintained means. :-)  I am hopeful that whoever does maintain mksnapshot can somehow get it to build for ARM now that electron-packager supports ARM, because I think that's the last roadblock preventing master-branch Atom from being compiled for armv7l.

**Comment by zeke** [comment]
@jkleinsc is actively working on resolving the mksnapshot issue, and I believe he cut a new release today.

**Comment by mathuin** [comment]
I find that very exciting!  What can I do to test it?

**Comment by jkleinsc** [comment]
Starting with version 1.8.5 (as well as 2.0.0-beta7), we changed how we distribute the arm/arm64 binaries of mksnapshot.  There are now 4 files for arm/arm64 mksnapshot, for example the following from the 2.0.0 release:

* `mksnapshot-v2.0.0-linux-arm-x64.zip` - intel x64 binary that produces snapshots suitable for using on armv7 hardware.
* `mksnapshot-v2.0.0-linux-arm.zip` - armv7 binary that produces snapshots suitable for using on armv7 hardware.
* `mksnapshot-v2.0.0-linux-arm64-x64.zip` - intel x64 binary that produces snapshots suitable for using on armv8(arm64) hardware.
* `mksnapshot-v2.0.0-linux-arm64.zip` -armv8(arm64) binary that produces snapshots suitable for using on armv8(arm64) hardware.

Because of these changes, when you now run npm install with an `electron-mksnapshot` dependency on arm or arm64 hardware you will get the binary that can actually run on those platforms.
